# Generated by Django 5.1.4 on 2024-12-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_groups_seller_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
